"""Change Float to Numeric for monetary fields

Revision ID: bb939531358c
Revises: 
Create Date: 2025-08-08 19:07:29.380117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb939531358c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'stake_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('games', 'bank_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('games', 'commission_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::real"))
    op.create_foreign_key(None, 'referral_earnings', 'users', ['referrer_id'], ['id'])
    op.create_foreign_key(None, 'referral_earnings', 'users', ['referral_id'], ['id'])
    op.create_foreign_key(None, 'referral_earnings', 'games', ['source_game_id'], ['id'])
    op.create_foreign_key(None, 'rolls', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'rolls', 'games', ['game_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'games', ['game_id'], ['id'])
    op.alter_column('users', 'balance',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.create_foreign_key(None, 'withdrawal_requests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawal_requests', type_='foreignkey')
    op.alter_column('users', 'balance',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'rolls', type_='foreignkey')
    op.drop_constraint(None, 'rolls', type_='foreignkey')
    op.drop_constraint(None, 'referral_earnings', type_='foreignkey')
    op.drop_constraint(None, 'referral_earnings', type_='foreignkey')
    op.drop_constraint(None, 'referral_earnings', type_='foreignkey')
    op.alter_column('games', 'commission_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'::real"))
    op.alter_column('games', 'bank_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('games', 'stake_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
